baseURL = 'https://erso-group.github.io/'
languageCode = 'en-us'
title = 'ERSO group'
theme = 'sustain'
publishDir = 'docs'

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/ERSO-group-logo-M.png"
  author = "Bret Staudt Willet"
  description = "ERSO Group's homepage created with blogdown and Hugo, featuring the Sustain theme."

  # Custom assets can be linked with their paths relative to static/
  custom_css = ["my.css"]
  custom_js  = []

[params.social]
  Twitter       = "ERSOgroup"
  Github        = "ERSO-group"
  Email         = "bret.staudtwillet@fsu.edu"
  LinkedIn      = ""
  Stackoverflow = ""
  Medium        = ""
  Telegram      = ""
  RSS           = "/news/index.xml"

## Main Menu
[[menu.main]]
  name = "news"
  weight = 100
  identifier = "news"
  url = "/news/"
[[menu.main]]
  name = "projects"
  weight = 200
  identifier = "projects"
  url = "/projects/"
[[menu.main]]
  name = "people"
  identifier = "people"
  weight = 300
  url = "/people/"
